import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "./components/navigation";
import { GeneralContextProvider } from "@/context/GlobalContext";
import "./globals.css";
import React from 'react';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <GeneralContextProvider>
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
    </GeneralContextProvider>
  );
}
